### ISSUE TITLE
Not all `id`s from `OpenAI` recognised

### ISSUE THREAD

**Issue by worikgh** [MrRobb/gym-rs#7]
I have been playing with `basic-rs` replacing `CartPole-v0` with envs from [OpenAI](https://gym.openai.com/envs/).  Some work some do not.  The ones that fail seem to fail here:

I had errors with:
* CarRacing-v0
* CarRacing-v0
 Both had same error
```
ModuleNotFoundError: No module named 'Box2D'
thread 'main' panicked at 'Could not make environment because of error:
expected value at line 1 column 1', examples/basic.rs:11:14
```

* Ant-v2
* Hopper-v2
 Both had same error
```
[2019-10-07 09:47:18,255] Making new env: Hopper-v2
/home/worik/.local/lib/python3.7/site-packages/gym/envs/registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
```

Apparently working:
* Acrobot-v1
* MountainCar-v0

Etcetera.

What can I do to help?

**Comment by worikgh** [comment]
[Here](https://github.com/openai/gym/issues/100) is solution.
`pip3 install box2d-py box2d-kengz Box2D` 
The reccomendation at that link is that you need `box2d-py` and NOT `Box2D`.  But I made most progress with them both.
Get another error:
```
TypeError: Object of type int64 is not JSON serializable
```

At: 
```
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
``` 
I think.  But python is all magic incantation to me so I do not think I can get further than that

**Comment by MrRobb** [comment]
Yes, I have managed to get it working by installing `box2d-py` and then editing the python script a little but I would like to make sure that there are no breaking changes. Sorry for the inconvenience, this is at a very early stage because the original repo [gym-http-api](https://github.com/openai/gym-http-api) seems to be abandoned.

This week I will try rebuilding the Python script to make it work properly and support the latest version of the dependencies. I will support [these environments](https://github.com/openai/gym/wiki/Table-of-environments). I don't know why it doesn't support the "Hopper-v2" and "Ant-v2". Maybe the version of the gym library.

Again, sorry for the inconvenience but just letting you know that I am actively working on it.

**Comment by MrRobb** [comment]
Even though I got it working the results are far from great because of an [issue in December of 2018](https://github.com/openai/gym/issues/1268). I think that working with the latest versions of the library will get rid of a lot of problems.

<img width="1312" alt="Screenshot 2019-10-07 at 11 22 49" src="https://user-images.githubusercontent.com/7969569/66304359-e13c4b00-e8f4-11e9-8024-d21f0c51da4d.png">

**Comment by MrRobb** [comment]
Hello @worikgh, the issues with `CarRacing-v0` are now solved. I have not been able to try the `Hopper-v2` because you need a [mojuco](https://github.com/openai/mujoco-py) license. I have asked for it, but it will take a while. Check out the [release notes](https://github.com/MrRobb/gym-rs/releases/latest).
